workflows:
  native-android:
    name: Native Android
    max_build_duration: 10
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "io.codemagic.sample.androidnative"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          ./gradlew clean createEmptyConfigFile pixel2api30DebugAndroidTest jacocoTestReport sonar