name: Android CI

on: [push]

jobs:

  unit-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: build and test
      run: |
        ./gradlew createEmptyConfigFile
        ./gradlew assembleDebug --stacktrace
        export CI=true
        ./gradlew pixel2api30DebugAndroidTest --stacktrace
        ./gradlew testDebugUnitTest --stacktrace
        ./gradlew jacocoTestReport --stacktrace
        ./gradlew :library:lintDebug --stacktrace
    - name: SonarCloud Scan
      run: |
        brew install sonar-scanner
        sonar-scanner
    - name: Store tests results
      uses: actions/upload-artifact@v1
      with:
        name: unit-test-results
        path: library/build/test-results/testDebugUnitTest
    - name: Store artifacts
      uses: actions/upload-artifact@v1
      with:
        name: additional-output
        path: library/build/outputs/managed_device_android_test_additional_output
    - name: Store merged test results
      uses: actions/upload-artifact@v1
      with:
        name: merged-test-results
        path: library/build/mergedReportDir
