name: Android CI

on: [push]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: build and test
      run: |
        ./gradlew createEmptyConfigFile
        ./gradlew assembleDebug --stacktrace
        export CI=true
        ./gradlew pixel2api30DebugAndroidTest --stacktrace
        ./gradlew testDebugUnitTest --stacktrace
        ./gradlew jacocoTestReport --stacktrace
        ./gradlew :library:lintDebug --stacktrace
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Store tests results
      uses: actions/upload-artifact@v1
      with:
        name: unit-test-results
        path: library/build/test-results/testDebugUnitTest
    - name: Store artifacts
      uses: actions/upload-artifact@v1
      with:
        name: additional-output
        path: library/build/outputs/managed_device_android_test_additional_output
    - name: Store merged test results
      uses: actions/upload-artifact@v1
      with:
        name: merged-test-results
        path: library/build/mergedReportDir

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: generate ksProp file
        run: python scripts/generateKsPropFile.py
      - name: create google-services.json file
        run: cat app/google-services.json | base64
      - name: update google-services.json file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json
      - name: Lint
        run: bash ./gradlew lintDebug
      - name: Lint results
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/reports/lint-results-debug.html

  ui-test:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: generate ksProp file
        run: python scripts/generateKsPropFile.py
      - name: create google-services.json file
        run: cat app/google-services.json | base64
      - name: update google-services.json file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > app/google-services.json
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
